// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire_tutorial

// Injectors from wire.go:

func InitializeEvent() (Event, error) {
	message := NewMessage()
	greeter := NewGreeter2(message)
	event, err := NewEvent2(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
